package com.training.exceptions;

import java.io.IOException;

public class TestException {
    public static void main(String args[]) throws IOException {
//        Testing manually created exception
        /*Voter voter = new Voter();
        voter.validateAge(10);
        System.out.println("Validation done");*/
        /*Divide divide = new Divide();
        divide.printQuotient(2,0);*/

        //Testing multiple catch exception
        /*MultipleCatch multipleCatch = new MultipleCatch();
        multipleCatch.TestMultiple(null, 3, 0);*/


//        Reading file and testing exception
        /*try {
            Filenotdemo filenotdemo = new Filenotdemo();
            filenotdemo.readfile("/Users/sumitkulhari/IdeaProjects/Java_training/src/com/training/exceptions/input.txt");

        } catch (FileNotFoundException e) {
            System.out.println(e.getMessage());
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }*/



    }
}
